### ISSUE TITLE
Foundation/core `group_prefix` should be `prefix` 

### ISSUE THREAD

**Issue by jknight-liatrio** [liatrio/terraform-caf-azure#50]
`prefix` is used everywhere. There should at least be consistency here.

https://github.com/liatrio/terraform-caf-azure/blob/0ae2afb90cf7c6bfc6ebab00510a6ca4c96bb1f8/foundation/core/variables.tf#L1

**Comment by christopherswarren** [comment]
https://github.com/liatrio/terraform-caf-azure/pull/61
